# Generated by Django 5.1 on 2024-09-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_comments_owner_remove_listing_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='active',
            field=models.BooleanField(auto_created=True, default=True),
            preserve_default=False,
        ),
    ]
