# Generated by Django 5.1 on 2024-09-18 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listing_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='best_bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='best_bidder', to=settings.AUTH_USER_MODEL),
        ),
    ]
