# Generated by Django 5.1 on 2024-09-18 13:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listing_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='watchlist',
        ),
        migrations.AddField(
            model_name='listing',
            name='watchlisted_users',
            field=models.ManyToManyField(blank=True, related_name='watchlisted_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
